name = "francekhalil"
compatibility_date = "2024-12-19"
pages_build_output_dir = "dist"

[[d1_databases]]
binding = "DB"
database_name = "francekhalil-db"
database_id = "815e23e6-e4fd-4e78-83fe-2df3677d1da7"

[vars]
ENVIRONMENT = "development"